# Generated by Django 5.1.3 on 2024-12-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_rename_new_price_product_sale_price_product_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
