# Generated by Django 5.1.3 on 2024-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_total_price_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_info',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
