# Generated by Django 5.1.3 on 2024-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_email_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='shipping_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
