# Generated by Django 5.1.3 on 2024-12-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(default='', max_length=100),
        ),
    ]
