# Generated by Django 5.1.3 on 2024-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
