# Generated by Django 5.1.3 on 2024-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_shippinginfo_session_key_alter_shippinginfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='address',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
