# Generated by Django 5.1.3 on 2024-12-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_rename_address_shippinginfo_address_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
